### ISSUE TITLE
Unable to create client in Admin

### ISSUE THREAD

**Issue by GioviQ** [IdentityServer/IdentityServer4.Templates#75]
dotnet new is4admin

Try with Chrome, Edge, Internet Explorer
![Annotazione 2020-03-22 115158](https://user-images.githubusercontent.com/7103057/77248068-f7d22680-6c36-11ea-837e-2e008edb4dbd.jpg)

**Comment by leastprivilege** [comment]
@scottbrady91

**Comment by scottbrady91** [comment]
@JosephHarvey

**Comment by forgetwholesale** [comment]
ugh.

I debugged into this issue, and apparently there was some json being returned which could not be parsed.

That json included text for the call stack for an exception.  Which looks like this (only including the top few lines):

System.InvalidOperationException: Synchronous operations are disallowed. Call ReadAsync or set AllowSynchronousIO to true instead.
↵   at Microsoft.AspNetCore.Server.IIS.Core.HttpRequestStream.Read(Byte[] buffer, Int32 offset, Int32 count)
↵   at Microsoft.AspNetCore.Server.IIS.Core.WrappingStream.Read(Byte[] buffer, Int32 offset, Int32 count)
↵   at System.IO.StreamReader.ReadBuffer()
↵   at System.IO.StreamReader.ReadToEnd()
↵   at IdentityExpress.Manager.Api.Formatters.JsonInputFormatter`1.ReadRequestBodyAsync(InputFormatterContext context, Encoding encoding)

Googling the InvalidOperationException turns up the following stackoverflow link:
https://stackoverflow.com/questions/47735133/asp-net-core-synchronous-operations-are-disallowed-call-writeasync-or-set-all

So, the fix for this is to add the AllowSynchronousIO line in bold (below) to the code within Startup.cs:

            // configures IIS in-proc settings
            services.Configure<IISServerOptions>(iis =>
            {
                iis.AuthenticationDisplayName = "Windows";
                iis.AutomaticAuthentication = false;
                **iis.AllowSynchronousIO = true;**
            });

**Comment by JosephHarvey** [comment]
Thanks for investigating this.

We plan to release AdminUI 3.0 early next week, alongside that we will be updating community edition with our latest AdminUI changes which will contain a fix for this issue.

**Comment by scottbrady91** [comment]
Thanks again for reporting this. This has been addressed in #76.

**Comment by leastprivilege** [comment]
Working on templates this week. Will release a new version with the Admin UI bits.
